### ISSUE TITLE
Como desenvolvedor, que seja inserido um indice na pagina quiz com todas as questões

### ISSUE THREAD

**Issue by Agathawei070** [Titus-System/1Semestre-ADS#85]

**Comment by pedro-fs-garcia** [comment]
precisei consertar umas coisas no backend do quiz para ficar mais fácil de fazer futuras mudanças e adicionar as questões

**Comment by pedro-fs-garcia** [comment]
a inclusão do indice em si não foi demorada, o que levou mais tempo foi a reorganização do backend
tempo: 3 horas
